name: deployer project 1    # Nom du workflow
on:                         # Les déclencheurs
    workflow_dispatch:      # déclencheur manuel
    push:                   # déclencheur push
      branches:
        - main
      paths:
        - projects/project_1/*.sh

jobs:                          # declaration des job
  verif_project_1:             # nom du 1er job
    runs-on: ubuntu-latest     # environnement d'execution
    steps:                     # declaration des steps
      - name: Checkout
        uses: actions/checkout@v4
      - name: action affiche
        run : ls projects/project_1/*.sh
