name: deployer project 1
on:
    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - projects/project_1/*.sh

jobs:
  verif_project_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: action affiche
        run : ls db/alter/*.sh
