name: deployer all
on:
#    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - projects/project_1/trigger.txt
        - projects/project_2/trigger.txt

jobs:
  verif_project_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter1
        uses: dorny/paths-filter@v3
        with:
          filters: |
            project_1:
              - 'projects/project_1/**'
      - name: action affiche
        if: steps.filter.outputs.project_1 == 'true'
        run : ls projects/project_1/*.sh

  verif_project_2:
    runs-on: ubuntu-latest
    needs: verif_project_1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter2
        uses: dorny/paths-filter@v3
        with:
          filters: |
            project_2:
              - 'projects/project_2/**'
      - name: action affiche
        if: steps.filter.outputs.project_2 == 'true'
        run : ls projects/project_2/*.sh