name: deployer all
on:
    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - projects/project_1/**
        - projects/project_2/**

jobs:
  verif_project_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            directoryChanges:
              - 'projects/project_1/**'
      - name: action affiche
        if: steps.filter.outputs.directoryChanges == 'true'
        run : ls projects/project_1/*.sh

  verif_project_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            directoryChanges:
              - 'projects/project_2/**'
      - name: action affiche
        if: steps.filter.outputs.directoryChanges == 'true'
        run : ls projects/project_2/*.sh