name: deployer all sec
on:
    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - projects/project_1/*.sh
        - projects/project_2/*.sh

jobs:
  verif_project_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: action affiche
        run : |
          ls projects/project_1/*.sh
          echo ${{github.repository_owner}}
          echo ${{ github.repository }}
          echo ${{github.repository_owner}}/${{ github.repository }}/.github/workflows/job_re_use.yml

  verif_project_2:
    runs-on: ubuntu-latest
    needs: verif_project_1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: action affiche
        run : ls projects/project_2/*.sh