name: deployer all
on:
#    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - projects/project_1/trigger.txt
        - projects/project_2/trigger.txt

jobs:
  verif_project_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter1
        uses: dorny/paths-filter@v3
        with:
          filters: |
            project_1:
              - 'projects/project_1/**'
      - name: action affiche
        if: steps.filter1.outputs.project_1 == 'true'
        run: echo "job 1 is succes"

  verif_project_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changes
        id: filter2
        uses: dorny/paths-filter@v3
        with:
          filters: |
            project_2:
              - 'projects/project_2/**'
      - name: action affiche
        if: steps.filter2.outputs.project_2 == 'true'
        run: echo "job 2 is succes"


  lance_job_1:
    needs: verif_project_1
    uses: ./.github/workflows/job_re_use.yml
    with:
      RELEASE_NAME: ${{ github.ref_name }}
    secrets:
      MA_VAR_SECRET: ${{ secrets.TEST_SECRET}}

  lance_job_2:
    needs: verif_project_2
    uses: ./.github/workflows/job_re_use.yml
    with:
      RELEASE_NAME: ${{ github.ref_name }}
    secrets:
      MA_VAR_SECRET: ${{ secrets.TEST_SECRET}}

